### ISSUE TITLE
input__clear is over under scroll line

### ISSUE THREAD

**Issue by alexbaumgertner** [bem-site/bem-forum#35]
![2014-09-02 12-12-31 current call](https://cloud.githubusercontent.com/assets/223620/4115521/143c2058-3279-11e4-8d37-4c006365c146.png)

**Comment by alexbaumgertner** [comment]
Hot fix:
add to https://github.com/bem/bem-forum/blob/master/desktop.blocks/comment/__edit-form/comment__edit-form.roo

``` css
.comment__edit-form .input_theme_normal.input_size_l .input__clear
{
    margin-right: 15px;
}
```
